import {mkdir} from 'node:fs/promises'
import {build} from 'esbuild'

await mkdir('dist', {recursive: true})

await Promise.all(
  ['main', 'daemon', 'post'].map(entry =>
    build({
      entryPoints: [`src/${entry}.ts`],
      outfile: `dist/${entry}.js`,
      bundle: true,
      platform: 'node',
      target: 'node24',
      format: 'esm',
      sourcemap: false,
      minify: true,
      legalComments: 'inline',
      banner: {
        js:
          "import {createRequire as __brcCreateRequire} from 'node:module';" +
          'const require=__brcCreateRequire(import.meta.url);' +
          '// Generated by npm run build. Do not edit directly.'
      }
    })
  )
)
